### ISSUE TITLE
Extracting connected components from `propr` objects

### ISSUE THREAD

**Issue by grayfall** [tpq/propr#16]
Greetings. I've been reading the reference manual to find a built-in method for cluster-extraction, but I haven't found anything useful. Basically, I need a way to transform a `propr` object into a list of vectors, wherein each vector is a connected component/cluster. Am I missing something? Right now I'm thinking about using `getAdj` to extract an adjacency matrix and extract connected components myself.

**Comment by tpq** [comment]
G'day,

For maximum control of the clustering procedure, I recommend pulling the `propr` matrix straight from the object. You can then cluster on this using any method you like. For big objects, I've had luck with the `fastcluster` package on CRAN.

```
library(propr)
data(iris)
pr <- propr(iris[,1:4])
pr@matrix
```

**Comment by grayfall** [comment]
@tpq Thanks for responding. I went with applying MCL to the adjacency matrix to remove weak connections prior to clustering, but I get the general point.
