### ISSUE TITLE
Add partial correlations to propr

### ISSUE THREAD

**Issue by danfulop** [tpq/propr#31]
**New feature request:**
Add partial correlations to propr, as detailed in this paper: [https://www.sciencedirect.com/science/article/pii/S2590197420300082]

I'm not sure if I can be of help with this, but I'd like to.

**Comment by tpq** [comment]
Thanks Dan, this thread will head me keep things organized. Ping @ionase @suzannejin 

Ionas, do you have a small minimal example of some R code you could share here?

My initial thoughts,
> The goal would be to pass the output of Ionas's parcor method to a propr object, and populate the @ slots accordingly. Once the @ slots of the propr object are populated (such as propr@logratio, propr@fdr, etc.) -- we can use existing methods like updateCutoffs will become available for FDR calculation.
> It should be sufficient to call parcor like propr(counts, metric = "parcor") or similar... unless the routines are distinct enough to warrant a separate call function such as parcor(counts).

**Comment by suzannejin** [comment]
Hey @tpq ,

So what I have been doing so far is to add the methods I want in propr(counts, metric="pcor"), something like:
```
propr <- function(counts, metric = c("rho", "phi", "phs", "cor", "vlr", "pcor", "pcorshrink"),
                  ivar = "clr", select, symmetrize = FALSE, alpha, p = 100){

[...]

  if(metric == "rho"){
    mat <- lr2rho(lr)
  }else if(metric == "phi"){
    mat <- lr2phi(lr)
    if(symmetrize) symRcpp(mat) # optionally force symmetry
  }else if(metric == "phs"){
    mat <- lr2phs(lr)
  }else if(metric == "cor"){
    mat <- stats::cor(lr)
  }else if(metric == "vlr"){
    mat <- lrv
  }else if(metric == "pcor"){
  mat <- ppcor::pcor(lr)$estimate.  # partial correlation with no regularization
  }else if(metric == "pcorshrink"){
  mat <- corpcor::pcor.shrink(mat) # partial correlation with regularization to correct for p>>n
  }else{
    stop("Provided 'metric' not recognized.")
  }
 [...]
}

```

However, it is a bit annoying when one wants to try out many different methods during the exploration step. Also, if we keep adding methods, the number of extra arguments (eg. corpcor has a lambda argument to define the regularization) will increase a lot.

For a more flexible approach, maybe we can separate the propr framework into different parts to allow users to use whatever association metric they want:
1) Part I - pre-processing of the data matrix, eg. CLR transformation, zero replacement, and other necessary checks.
2) Part II - computation of proportionality/pearson/partial correlation/etc coefficients. This can be done by either calling the corresponding propr function, or computing the coefficient with an external package by the user itself.
3) Part III - populate @ slots
4) Part IV - UpdateCutoffs

Another option (it has just occurred to me, so I have never tried it out, but I think this might be the cleanest approach) is to  use a function as an argument for propr, something like:
```
propr <- function(counts, metric = c("rho", "phi", "phs", "cor", "vlr", "pcor", "pcorshrink"), FUN=NA,
                  ivar = "clr", select, symmetrize = FALSE, alpha, p = 100){
 [...]
  if (!is.na(FUN)){
    mat <- FUN(lr)
   ## add some checks, and warnings to avoid errors 
  }else{
    # run proportionality as above
  }
 [...]
}

# user-defined function
partialcor <- function(counts, lambda=NA, ...){
  if (!is.na(lambda)){
    mat = corpcor::pcor.shrink(counts)
  }else{
   mat = corpcor::pcor.shrink(counts, lambda=lambda)
  }
  return(mat)
}

# call propr
propr(counts, FUN=partialcor, ...)
```

**Comment by tpq** [comment]
Looking good!!!!!

It is possible to pass along sets of arguments this way...

```
propr <- function(counts, metric = c("rho", "phi", "phs", "cor", "vlr", "pcor", "pcorshrink"),
                  ivar = "clr", select, symmetrize = FALSE, alpha, p = 100, ...){
  }else if(metric == "pcor"){
  mat <- ppcor::pcor(lr)$estimate.  # partial correlation with no regularization
  }else if(metric == "pcorshrink"){
  mat <- corpcor::pcor.shrink(mat, ...) # partial correlation with regularization to correct for p>>n
}
```

Using `...`, any additional named arguments will get pass through to the method called by the user (either pcor or pcorshrink). This allows the user to customize propr() calls without us having to accommodate every possible argument.

PS: possible typo -- i assume it should read `pcor.shrink(lr)` not `pcor.shrink(mat)`?

To me, option 1 seems like the path of least resistance. If I push such a change to GitHub, would you be able to run some tests to check if it works as expected?

**Comment by suzannejin** [comment]
Sure, if you are gonna push a change, I can do the test.

And, indeed it is a typo.

One question, if we pass `...` arguments, these arguments have to be properly called inside propr right? so we have to define how they should be managed inside propr beforehand?

**Comment by tpq** [comment]
Thanks! I'll get on it shortly.

Regarding your question about `...`, most everything gets handled automatically.

I made this little code snippet as an example:

```
dist_wrapper <- function(x, ...){
  
  dist(x, ...)
}
mat <- matrix(1:30, 5, 6)
dist_wrapper(mat)
dist_wrapper(mat, method = "manhattan")
```

**Comment by suzannejin** [comment]
okay, I see. Thanks!!

It looks like a nice way to do it! Although I think it could be good to also add option 3 to input a user-defined function. In this case, the user will have the already defined functions like proportionality, pearson, partial correlation, and then the possibility to test other approaches without the need to keep updating the propr code all the time. What do you think?

**Comment by tpq** [comment]
I think it is a double-edged sword. If you provide more functionality, you may have less maintenance in a sense. But things can wrong in unexpected ways, which tends to increase maintenance! I'll have a think though whether there is a clean way to do it.

**Comment by tpq** [comment]
PS Suzanne, i would like to add you at a contributor to the package as a thanks for your all your help. It's something you can list on your C.V. when you apply to jobs as evidence you have taken the time to contribute to open-source software development. What first / last name and e-mail address do you prefer?

**Comment by suzannejin** [comment]
> PS Suzanne, i would like to add you at a contributor to the package as a thanks for your all your help. It's something you can list on your C.V. when you apply to jobs as evidence you have taken the time to contribute to open-source software development. What first / last name and e-mail address do you prefer?

Thanks a lot Thom!!! This would be great!! Please use "Suzanne Jin" and suzanne.jin.yao@gmail.com

**Comment by tpq** [comment]
Writing to confirm that 4.2.9 is now pushed with pcor support. I have not tested it though! Hoping @suzannejin  and maybe @danfulop would help with that ^_^

**Comment by suzannejin** [comment]
Sure! I will run the test asap!!  :)

**Comment by suzannejin** [comment]
Hey Thom, I have tested the new code on my datasets. It is working properly except for the FDR calculation, since it considers the new metrics as good for low values (when it should be the contrary). I corrected this in my pull request. Please have a look

**Comment by danfulop** [comment]
UGH, I just noticed all this action. I wasn't being notified about any of these changes. I'm so sorry! I guess I have all github email notifications turned off. I'm more than happy to test the next code update.

**Comment by tpq** [comment]
No worries at all.

Thank you both for your interest in making this happen. Let me know if you get any good mileage about of the new feature 🥇
