### ISSUE TITLE
any option for robust or weighted metrics?

### ISSUE THREAD

**Issue by rsiani** [tpq/propr#40]
Hi,
I am currently dealing with a “complicated” dataset. I had a decent amount of RNAseq samples to start with, but I ended up with very unequal sample sizes and a few other sequencing complication which made the data quite noisy. 

My current workaround is to discard “unsalvageable” samples and calculating DEGs using the bias in sequencing intensity as weights in the regression. 

This kinda work in a univariate framework, as I can circumvent problems with low counts being less informative, as long as the assumption of library size == quality holds. I guess voom is using a somehow similar approach.

Anyhow, the trick works fine for univariate analyses, but I haven't figured out how to extend it to propr.  If I got it correctly, propr relies on finding proportionality among genes which are stable across the samples. So by "informing" the program about which samples I believe to be more reliable, I would have more robust results. I assume I could just look into the code and replace estimates with their weighted counterparts. But of course I wanted an expert opinion before butchering your code...

Thanks!

**Comment by tpq** [comment]
Thanks for your interest in propr. Proportionality is a useful way of measuring the association between variables of compositional data. However, it does not currently have a method for accounting for sequencing depth as a measure of quality.

That said, here are a few thoughts:
- In the case that you have established a method to normalize the data effectively, you could measure the correlation or proportionality between the normalized variables directly.
- In the case that you have a set of _variables_ (as opposed to samples) that could be used as a normalizing reference, you could run propr in additive log-ratio (alr) mode.
- Given that propr finds associations between variables irrespective of a supervised label, you could exclude the "unsalvageable" samples entirely.
- You could look for associations only within the data set having more sample sizes.

Hope this helps some!

**Comment by rsiani** [comment]
I guess option 3 suits better... Maybe once I feel more confidant in my statistical and coding skill I could try to find a more exact solution.

But I guess the general problem is always the same, it's still not even sure if normalizing sequencing data is actually feasible. On top of that, transformations only help up to a certain point (I have read your material on each coming with a baggage of assumptions...). 

Looking forward to trying the new aldex scaling feature though!

Thanks again Thomas!
