### ISSUE TITLE
How do we download and install?

### ISSUE THREAD

**Issue by mpage21** [tpq/propr#47]
This might be a silly question, but how do I download and install propr? It seems it was removed from the CRAN repository in 2022: [https://cran.r-project.org/package=propr](https://cran.r-project.org/package=propr``), so I'm just wondering how I'm now supposed to download and install this. Thank you for your help

**Comment by tpq** [comment]
Yes, sorry! We are in the process of up-lifting the software and getting it back on CRAN.

You can still install it directly from GitHub via

```
install.packages("devtools")
devtools::install_github("tpq/propr")

```

**Comment by mpage21** [comment]
Thank you!
