### ISSUE TITLE
Would it not be good to use dgCMatrix instead of a matrix in your class?

### ISSUE THREAD

**Issue by stela2502** [tpq/propr#5]
Hi,
I am trying to use your package on real single cell data and it is not exactly fast.
I wonder whether you could significantly speed up your package by converting from the usage of matrix to Matrix (or more clear: a sparse dgCMatrix).
My package https://github.com/stela2502/FastWilcoxTest could be used as an example of how to interact with this sparse matrix from within c++.
The speed up if you do not need to convert from a sparse matrix to a conventional is quite nice!

**Comment by tpq** [comment]
Hi Stela,

Thanks for your interest. Although I put a lot of work into making propr run fast, I'm sure there are many ways to improve its performance further. However, I am not sure whether a sparse matrix is the way forward? A fundamental assumption underlying the methods presented in propr is that the matrix contains no zeros (all zeros must get imputed prior to or during analysis).

When you say "not exactly fast", could you please describe the dimensions of your data? From my own benchmarks, propr() usually runs almost as fast as the base R cor() function.

Cheers,
Thom
