### ISSUE TITLE
Shrunken plots in vignettes 

### ISSUE THREAD

**Issue by adriaaula** [tpq/propr#7]
At CRAN the plots in the vignettes are really small and I am unable to see the results: 

https://cran.r-project.org/web/packages/propr/index.html
https://cran.r-project.org/web/packages/propr/vignettes/b_visualization.html

Is there another option for checking the vignettes? I have tried the following and it didn't work either: 

```
library(propr)
browseVignettes("propr")
help(package = "propr", help_type = "html")
```

I have `propr_4.1.5` installed! 

Thanks :)

**Comment by tpq** [comment]
Hi Adria,

Thanks for your interest in propr.

Ha! Yes, the plots are EXTREMELY small... (the reason for this is that CRAN sets a limit on the size of the package, including vignette figures). One option is to run the vignette .Rmd directly -- e.g.,
https://raw.githubusercontent.com/tpq/propr/master/vignettes/b_visualization.Rmd

If you delete the "dpi = 66", you should be able to "knit" the vignette at a higher resolution.

Hope this helps!

Cheers,
Thom
